### ISSUE TITLE
Beat queue does fail rarely parsing the JSON while beating

### ISSUE THREAD

**Issue by jimdevops19** [red-hat-storage/rlockertools#6]
Rarely, this error occurs while beating to a queue while it is in pending state:
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-trigger-test-pr@2/rlock-tools/venv/bin/rlock", line 8, in <module>
    sys.exit(main())
  File "/home/jenkins/workspace/qe-trigger-test-pr@2/rlock-tools/venv/lib64/python3.8/site-packages/framework/main.py", line 163, in main
    run(args)
  File "/home/jenkins/workspace/qe-trigger-test-pr@2/rlock-tools/venv/lib64/python3.8/site-packages/framework/main.py", line 128, in run
    verify_lock = inst.wait_until_finished(
  File "/home/jenkins/workspace/qe-trigger-test-pr@2/rlock-tools/venv/lib64/python3.8/site-packages/rlockertools/resourcelocker.py", line 291, in wait_until_finished
    self.beat_queue(queue_id)
  File "/home/jenkins/workspace/qe-trigger-test-pr@2/rlock-tools/venv/lib64/python3.8/site-packages/rlockertools/resourcelocker.py", line 411, in beat_queue
    pp.pprint(req.json())
  File "/home/jenkins/workspace/qe-trigger-test-pr@2/rlock-tools/venv/lib64/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jimdevops19** [comment]
Closing this, as we did not meet this one again in the last 75 days
