### ISSUE TITLE
failed to get with queue doen't exist

### ISSUE THREAD

**Issue by vavuthu** [red-hat-storage/rlockertools#9]
failed to get lock with below error

```
Queue 302 does not exist on the server! 
Error is not recoverable, raising Exception 
Please check the logs of the Django application! 
Possible solutions: 
 - Please double check your search_string, that it matches to an existing label or name
An unexpected error occured!
Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/rlock-tools/venv/bin/rlock", line 8, in <module>
    sys.exit(main())
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/rlock-tools/venv/lib64/python3.8/site-packages/framework/main.py", line 163, in main
    run(args)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/rlock-tools/venv/lib64/python3.8/site-packages/framework/main.py", line 128, in run
    verify_lock = inst.wait_until_finished(
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/rlock-tools/venv/lib64/python3.8/site-packages/rlockertools/resourcelocker.py", line 257, in wait_until_finished
    raise Exception(
Exception: Queue 302 does not exist on the server! 
```

**Comment by jimdevops19** [comment]
This has occurred because of temporary networking issues of the OCP. However, we should leave this issue open because of wrong Exception catching, because there should be a different exception raised.

**Comment by jimdevops19** [comment]
Closing this as we did not see this in the last 70-75 days, probably was a temporary connection issue
